
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 18 09:07:20 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FSI = 36;
  public static final int TANTQUE = 30;
  public static final int CROFER = 9;
  public static final int MULT = 4;
  public static final int POUR = 29;
  public static final int EGAL = 10;
  public static final int REPETER = 31;
  public static final int SI = 33;
  public static final int VIRGULE = 12;
  public static final int FIN = 25;
  public static final int CSTEBOOL = 22;
  public static final int OU = 18;
  public static final int INF = 14;
  public static final int NON = 19;
  public static final int PAROUV = 6;
  public static final int CLASS = 24;
  public static final int DIV = 5;
  public static final int EGALEGAL = 15;
  public static final int PLUS = 2;
  public static final int ECRIR = 38;
  public static final int DEBUT = 27;
  public static final int EOF = 0;
  public static final int LIR = 37;
  public static final int error = 1;
  public static final int CSTEINT = 21;
  public static final int MOINS = 3;
  public static final int ET = 17;
  public static final int PRIVEE = 40;
  public static final int SINON = 35;
  public static final int IDF = 20;
  public static final int ALORS = 34;
  public static final int PARFER = 7;
  public static final int CROOUV = 8;
  public static final int POINTVIRGULE = 11;
  public static final int FINTANTQUE = 32;
  public static final int SUP = 13;
  public static final int PUBLIQUE = 39;
  public static final int DIFF = 16;
  public static final int ENTIER = 26;
  public static final int NOUVEAU = 28;
  public static final int CSTECHAINE = 23;
}

