
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 16 17:02:03 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FSI = 33;
  public static final int TANTQUE = 27;
  public static final int MULT = 4;
  public static final int POUR = 26;
  public static final int EGAL = 8;
  public static final int REPETER = 28;
  public static final int SI = 30;
  public static final int VIRGULE = 10;
  public static final int FIN = 23;
  public static final int CSTEBOOL = 20;
  public static final int OU = 16;
  public static final int INF = 12;
  public static final int NON = 17;
  public static final int PAROUV = 6;
  public static final int CLASS = 22;
  public static final int DIV = 5;
  public static final int EGALEGAL = 13;
  public static final int PLUS = 2;
  public static final int ECRIR = 35;
  public static final int DEBUT = 25;
  public static final int EOF = 0;
  public static final int LIR = 34;
  public static final int error = 1;
  public static final int CSTEINT = 19;
  public static final int MOINS = 3;
  public static final int ET = 15;
  public static final int PRIVEE = 37;
  public static final int SINON = 32;
  public static final int IDF = 18;
  public static final int ALORS = 31;
  public static final int PARFER = 7;
  public static final int POINTVIRGULE = 9;
  public static final int FINTANTQUE = 29;
  public static final int SUP = 11;
  public static final int PUBLIQUE = 36;
  public static final int DIFF = 14;
  public static final int ENTIER = 24;
  public static final int CSTECHAINE = 21;
}

